### ISSUE TITLE
The big TODO list

### ISSUE THREAD

**Issue by NaamloosDT** [NaamloosDT/DSharpPlus#42]
So @Emzi0767 gave me some ideas for future versions of the library. These ideas should further improve the library in a lot of ways. I'm excited!

Here's a "little" checklist:
- [x] Incoming voice
- [x] Organize class members so that they are not all over the place, but are ordered according to some key. No effect on end-users, and will make maintenance easier.
- [x] Make all entities immutable, and perform mutation via events only. This is potentially mildly breaking, but it will also eliminate some weird cases.
- [x] Implement a message cache.
- [x] Abstract data structures. This will make maintenance infinitely easier. No effect on end-users.
- [x] Port VoiceNext to 2.x
- [x] `.SetMute` and `.SetDeaf` methods for DiscordMembers
- [x] Multi file uploading (to one message ofc)
- [x] Settle on argument naming. I'm in favour of snake_case. Shouldn't affect compatiblity.
- [x] Setting on private field naming. Ditto as above.
- [x] Rename all awaitable methods to `...Async()`. This could be potentially breaking, but it'd help reduce confusion by making it clear what needs to be awaited and what doesn't.
- [x] Split the websocket and REST parts of the client for API communication. No effect on end-user, but will make classes smaller and easier to maintain.
- [x] make `DiscordMember` inherit from `DiscordUser` rather than wrap it. This is going to make working with members infinitely easier.
- [x] Docs overhaul
- [x] Command overhaul
- [x] More example bots
- [x] Support for different .NET versions, including .NET core
- [x] Discord character limits
- [x] Fix caches
- [x] Sharding support
- [x] Autosharding support

As emzi stated, the lib has grown quite a bit, and its code organization is messy.

If any of you have any other ideas, leave them as comments.
Also: if anything listed gets implemented, also leave a comment so i can edit the main message.

Thank you

**Comment by NaamloosDT** [comment]
Also, if any of the other devs want to make a big comeback ( :^) ), I'll assign you to this issue too.

**Comment by Bond-009** [comment]
Maybe .Net Core support? (netstandard)

**Comment by NaamloosDT** [comment]
@Bond-009 ah, yes. .NET core support is planned. Haven't added it to the list yet though. Thanks.

**Comment by Emzi0767** [comment]
Also:

* Incoming voice
* Docs overhaul (working on it atm)
* Command overhaul
* More example bots

**Comment by NaamloosDT** [comment]
@Emzi0767 added them to the checklist

**Comment by NaamloosDT** [comment]
Added RPC. Not sure. Might be nice for some apps?

**Comment by Emzi0767** [comment]
It might, although if we end up doing this, we'll prolly put it as a module, since RPC is different from everything else.

**Comment by NaamloosDT** [comment]
Yeah I figured

**Comment by NaamloosDT** [comment]
I'm adding message limits to the checklist. e.g. preventing users from sending messages that exceed the chraracter limit

**Comment by NaamloosDT** [comment]
snake_case is done

**Comment by NaamloosDT** [comment]
Added "fix caches"

**Comment by JustArchi** [comment]
Since I don't have any better place to say this and I don't feel like creating another issue for it, I'd just want to say big thank to all of you guys for making this library work perfectly with my Mono setup ❤️. I hope I didn't clutter todo list issue too much with this message, please keep being awesome! 🎉

**Comment by NaamloosDT** [comment]
@JustArchi you're welcome! Thanks for taking interest in the library :)

**Comment by NaamloosDT** [comment]
Added sharding support to the to do list because it's pretty much essential

**Comment by NaamloosDT** [comment]
Removed Discord RPC from the list

**Comment by NaamloosDT** [comment]
Moved finished topics down the list. please do this if you complete one of these tasks.

**Comment by YourAverageBlackGuy** [comment]
Try and add a .setMute() and .setDeaf() method for the GuildMember object that server mutes/deafens. The parameter could be a bool that decides whether to mute or not.

**Comment by NaamloosDT** [comment]
@YourAverageBlackGuy Your ideas have been added to the checklist 👌

**Comment by OmniKahedron** [comment]
Function / Property for DiscordMember that returns the member's name color (or 0 if default)

(Assuming the DiscordMember instance knows what DiscordGuild it belongs to)

Also Display name, aka just this.Nickname ?? this.Username

(Because that's tidier than making a static method for that somewhere)

**Comment by OmniKahedron** [comment]
Turn DiscordMember.GetNameColor into a NameColor property (saves 5 characters and looks tidier)
(Also I suggest changing it to DisplayColor, sounds better idk)

DisplayName property for DiscordMember (https://www.hastebin.com/mimozajuwi.vbs ?)
Not "really" necessary but would be handy for commands

**Comment by Emzi0767** [comment]
We should implement a message cache. I added that to the list.

**Comment by Emzi0767** [comment]
Since it appears all immediate tasks are done, I will now close the issue.

**Comment by NaamloosDT** [comment]
WOOOOOOOO
